### PR TITLE
Sandbox scripts for Large eddy simulation

### PR DESCRIPTION
**Pull request by glwagner**
(and better boundary conditions API).

This PR adds two scripts to the sandbox for performing large eddy simulation of:

- [ ] a 'simple flux' scenario of a ~100 m square ocean forced by constant surface fluxes, and
- [ ] stratified Couette flow.

We may also want to add an example based on one of these scripts.

Addresses #310.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
All GPU tests pass on Supercloud.

I'm opposed to the `minute, hour, day` constants as they're specific to Earth (and are they used anywhere?) but otherwise looks good to merge. We can worry about them later.

**Comment by ali-ramadhan** [comment]
I'll start running some stratified Couette flow simulations.

**Comment by glwagner** [comment]
Only “day” is specific to Earth.

Do not merge. The scripts are not done yet.

**Comment by ali-ramadhan** [comment]
> Only “day” is specific to Earth.

That's true. If you think it's a good idea to include these constants, maybe `planetary_constants.jl` is a better place? `day` or `seconds_per_day` can sit inside the `PlanetaryConstants` struct.

**Comment by glwagner** [comment]
To be clear, the purpose of the constants is to support intuitive scripting patterns like

```julia
Δt = 10minute
finaltime = 4day
```

Changing `day` to `seconds_per_day` subverts this intent. I also think we need to be a little more sensitive to the effect that excessive verbosity has on code readability moving forward.

I am fine with moving the constants to `planetary_constants.jl`.

**Comment by jm-c** [comment]
Just to avoid confusion:
length (in second) of minute, hour and day are well defined, as well as the
"second" (but it's more complicated) and are independent of which planet you are. 
They are not "planetary constants".
On the other hand, the rotation period (which, BTW, on earth, is not 1 day
but ~86164.s, so a bit less) is a planetary constant.

**Comment by ali-ramadhan** [comment]
> Just to avoid confusion:
> length (in second) of minute, hour and day are well defined, as well as the
> "second" (but it's more complicated) and are independent of which planet you are.
> They are not "planetary constants".
> On the other hand, the rotation period (which, BTW, on earth, is not 1 day
> but ~86164.s, so a bit less) is a planetary constant.

Good points. I've been using `seconds_per_day = 86400` to count the number of days and impose time-varying forcings, when I suppose I meant to use the rotation period. `rotation_period` makes more sense a planetary constant.

**Comment by ali-ramadhan** [comment]
@glwagner I see you've added a JLD2 output writer but JLD2 (and FileIO if you use it) aren't listed as dependencies in `Project.toml` nor `Manifest.toml`.

We can also get rid of the JLD dependency since we nuked checkpointing in PR #282 and I forgot to remove it.

**Comment by glwagner** [comment]
Thanks @jm-c.

I’ve used “siderealday” in the past for that number. It seems the calendar day is the most important number for scripts and simulation set up. I haven’t used either sidereal day (or rotation period, equivalently) yet. 

I think planetary constants concepts is problematic and over-specific anyways for our humble code; we probably just want to have “constants”. Being more general will avoid confusion. 

Thanks for finding that @ali-ramadhan. Feel free to make those changes.

**Comment by ali-ramadhan** [comment]
Ah wait a second, JLD is still being used in `test_regression.jl` for `JLDOutputWriter` in `run_rayleigh_benard_regression_test`.

@glwagner do you want to switch that test to use the JLD2 output writer you added in this PR, or should I revert commit fb90c20c891542e34e601667071c8dc957beb8a1 and we can worry about this later.

**Comment by ali-ramadhan** [comment]
Do not merge yet. There's a GPU bug with `calc_diffusivities!`.

Since we now use `config=launch_config(grid, 3)`, the z loop needs to be
```julia
@loop for k in (1:grid.Nz; (blockIdx().z - 1) * blockDim().z + threadIdx().z)
```
instead of
```julia
@loop for k in (1:grid.Nz; blockIdx().z)
```
since `launch_config` will return block sizes where `Bz != Nz`.

Will commit a fix once I test it.

**Comment by ali-ramadhan** [comment]
Found another small bug where `get_κ` and `get_ν` were not defined for Smag and AMD so boundary conditions were being applied as if an `IsotropicDiffusivity` closure was in effect.

**Comment by glwagner** [comment]
@ali-ramadhan, smag and AMD are IsotropicDiffusivities.

**Comment by ali-ramadhan** [comment]
@glwagner I see why you made that choice. I can revert the commit.

I suspected it was causing my boundary condition to drift away from the imposed values, suggesting that the Dirchlet/Value boundary condition may not have been imposed correctly, but maybe there's another issue at play here.

**Comment by ali-ramadhan** [comment]
@glwagner `deepening_mixed_layer.jl` runs on Supercloud so I'll merge this PR.

**Pull request merged**
