### PR TITLE
Regression tests for models with LES closures

### LINKED ISSUE #473: LES regression test
Seems like a good idea to have an LES regression test for big PRs that modify the `TurbulenceClosures` module such as PR #452.

I guess we can use a coarse stratified Couette flow or free convection simulation in steady state to check for this.

### PR DESCRIPTION
**Pull request by glwagner**
This PR adds two regression tests for models that use the `ConstantSmagorinsky` closure and the `AnisotropicMinimumDissipation` closure. It also organizes the regression tests into a separate directory.

Resolves #473

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Hmmm, seems like tests are failing. Some with `KeyError: key "timeseries" not found` and some with file not found type errors.

**Comment by glwagner** [comment]
That error is a weird way to say that the file was not found. I moved around a few things and maybe some of those didn't stick. I'll get it working.

Yes, I think we should merge this before arbitrary tracers.

I think you're right that we should reduce `test_step!`.

I'll request another review when I make the changes.

**Comment by ali-ramadhan** [comment]
Seems that 8/10 LES regression tests pass. The `v` fails with AMD while the `w` test fails with Smagorinsky-Lilly...

This is pretty consistent across Travis CI (passes on Linux, fails on Mac), Appveyor, and GitLab CI (both CPU and GPU). So it's kind of OS-specific but seems pretty robust across different hardware.

But looking at the test log, the errors look fine: `Δv` and `Δw` are no larger than `~1e-13`.

I'm wondering if there's a zero entry in `v` and `w` resulting in an expression like `1e-15 ≈ 1e-25`. Both `1e-15` and `1e-25` are close enough to zero for this test, but `≈` would return false. This entry could be closer or further from zero depending on OS and architecture.

```
julia> 1 ≈ 1 + 1e-10
true
julia> 1e-15 ≈ 1e-25
false
```

Looking at how the regression data was generated, seems like it might have been good to initialize `v` with some noise. But `w=u₀` and it still fails...

Rather than regenerating the regression data maybe it'll be good to change the test to check for absolute error by using the `isapprox` function and passing a non-zero `atol`.

I can give this a try later this afternoon.

---

```
  Testing oceanic large eddy simulation regression [VerstappenAnisotropicMinimumDissipation, CPU]
[ Info: Δu: min=-1.14728e-13, max=1.62294e-13, mean=-1.09883e-20, absmean=2.12163e-14, std=2.76021e-14
[ Info: Δv: min=-1.5609e-13, max=1.08464e-13, mean=-2.75418e-20, absmean=2.0988e-14, std=2.72286e-14
[ Info: Δw: min=-1.80785e-13, max=1.97494e-13, mean=-1.62683e-19, absmean=3.17569e-14, std=4.27591e-14
[ Info: ΔT: min=-2.73559e-13, max=2.06057e-13, mean=-5.36897e-16, absmean=2.77339e-14, std=3.88347e-14
[ Info: ΔS: min=-1.13687e-13, max=7.81597e-14, mean=1.56125e-17, absmean=1.51424e-14, std=1.96383e-14
Ocean large eddy simulation [CPU]: Test Failed at /Users/travis/build/climate-machine/Oceananigans.jl/test/regression_tests/ocean_large_eddy_simulation_regression_test.jl:69
  Expression: all(Array(data((checkpointed_model.velocities).v)) .≈ Array(data((test_model.velocities).v)))
```

```
  Testing oceanic large eddy simulation regression [SmagorinskyLilly, CPU]
[ Info: Δu: min=-7.75408e-14, max=5.89303e-14, mean=-3.3749e-21, absmean=1.12211e-14, std=1.46851e-14
[ Info: Δv: min=-8.65072e-14, max=4.9561e-14, mean=1.44939e-20, absmean=1.1453e-14, std=1.46633e-14
[ Info: Δw: min=-9.09516e-14, max=1.64272e-13, mean=7.36786e-20, absmean=1.85036e-14, std=2.48686e-14
[ Info: ΔT: min=-1.74083e-13, max=2.06057e-13, mean=-2.37657e-16, absmean=1.79422e-14, std=2.66236e-14
[ Info: ΔS: min=-1.20792e-13, max=7.81597e-14, mean=-3.19189e-16, absmean=1.17857e-14, std=1.57889e-14
Ocean large eddy simulation [CPU]: Test Failed at /Users/travis/build/climate-machine/Oceananigans.jl/test/regression_tests/ocean_large_eddy_simulation_regression_test.jl:70
  Expression: all(Array(data((checkpointed_model.velocities).w)) .≈ Array(data((test_model.velocities).w)))
```

**Comment by ali-ramadhan** [comment]
Hmmm, gave it a try but tests pass on my laptop so not sure how to go about reproducing the failing tests...

**Comment by glwagner** [comment]
I think we may want to regenerate the regression data, and perhaps use `test_steps=10`. 

I can open a new PR that will avoid adding the old, unused regression data to the repo.

**Pull request closed without merging**
