### PR TITLE
New and more correct turbulence closures

### PR DESCRIPTION
**Pull request by glwagner**
This PR makes a few major contributions:

* Fixes a bug in Anisotropic Minimum Dissipation (AMD) type closures that led to (very) wrong subgrid-scale diffusivities.
* Adds a new flavor of AMD proposed by [Verstappen (2018)](https://www.sciencedirect.com/science/article/abs/pii/S0045793016304005) and described in detail by [Vreugdenhil and Taylor (2018)](https://aip.scitation.org/doi/abs/10.1063/1.5037039). This new flavor of AMD, dubbed the "Verstappen" AMD, is now the default name bound to `AnisotropicMinimumDissipation`
* The closure formerly known as `AnisotropicMinimumDissipation` is now called `RozemaAnisotropicMinimumDissipation` (it was first described by [Rozema et al. (2015)](https://aip.scitation.org/doi/abs/10.1063/1.4928700)). It is not exported, but can be accessed via `Oceananigans.RozemaAnisotropicMinimumDissipation`.
* There is new Smagorinsky closure variant called `BlasiusSmagorinsky` which is untested and unexported. It can be accessed via `Oceananigans.BlasiusSmagorinsky`.

### CODE REVIEW

**Comment by glwagner** [comment]
@ali-ramadhan the constants have slightly different meaning, which creates confusion --- let me explain:

* In the Rozema version of AMD, the 'filter width' `δ` is defined as the grid spacing. Thus on an isotropic grid, the eddy viscosity becomes

`ν = -C_roz * Δ^2 * r / q`,

where r and q are defined in equations (9) and (11) in [Rozema et al. (2015)](https://aip.scitation.org/doi/abs/10.1063/1.4928700)

* In the Verstappen version of AMD (and as described in Vreugdenhil and Taylor 2018), the 'filter width' `δ` is defined as *twice* the grid spacing for finite differences (and 3/2 for spectral discretization). Thus on an isotropic grid and with finite differences the Verstappen version of AMD reduces to

`ν = -C_ver * δ^2 * r / q = - 4 * C_ver * Δ^2 * r / q`

Thus in this case `C_ver = 1/12` is equivalent to `C_roz = 4/24 = 0.33`. 

On anisotropic grids, things can be slightly different.

I'm open to changing the implementation, but I'm not sure what the best route is. Possibly we will phase out the Rozema version... ?

**Comment by glwagner** [comment]
> @jm-c would know what constant to use for constant Smag combined with our numerical methods as it has been used in the MITgcm.

We were told that Smagorinsky has not been tested in MITgcm so I'm not sure that's true.

> Still not sure why TurbulenceClosures uses it's own differentiation and interpolation operators when we have Oceananigans.Operators.

Migrating to the other operators would have taken some time and effort and possibly involved bugs so I chose to keep the ones I was familiar with. I find the new operators a little more difficult to read than the ones we currently use, and I didn't want to have to worry about that when implementing complex new functions involved with the `VerstappenAnisotropicMinimumDissipation`.

**Comment by ali-ramadhan** [comment]
> Migrating to the other operators would have taken some time and effort and possibly involved bugs so I chose to keep the ones I was familiar with. I find the new operators a little more difficult to read than the ones we currently use, and I didn't want to have to worry about that when implementing complex new functions involved with the `VerstappenAnisotropicMinimumDissipation`.

Fair enough, I realize this was a decision made back when AMD was first implemented. Hopefully we'll find a way to merge the two in the future.

**Comment by ali-ramadhan** [comment]
Thanks for explaining why the `C` values are different, didn't realize that.

Not sure where it comes from but shouldn't it be `C_roz = 4/24 = 0.167` or `C_roz = 8/24 = 0.33`?

> I'm open to changing the implementation, but I'm not sure what the best route is. Possibly we will phase out the Rozema version... ?

Not sure how much code overlaps between the two, but if both are deemed important enough to maintain, then the shared functionality can go into `amd_core.jl` or something. Although probably a bad idea to do this refactor before each AMD closure has it's own regression test.

**Comment by glwagner** [comment]
> Not sure where it comes from but shouldn't it be C_roz = 4/24 = 0.167 or C_roz = 8/24 = 0.33?

Typo. 4 * 1/12 = 4/12 = 0.33.

**Comment by ali-ramadhan** [comment]
Looks good to merge!

**Comment by glwagner** [comment]
> Not sure how much code overlaps between the two, but if both are deemed important enough to maintain, then the shared functionality can go into amd_core.jl or something.

I considered this when I started developing the Verstappen closure. Almost none of the code is shared, which is why there are two files, unlike the Smagorinsky closures which have a lot of shared code. In principle it might be possible to refactor both implementations to share (a bit) more code but that would be a lot of work, and would also probably make both implementations more complex...

**Comment by ali-ramadhan** [comment]
> I considered this when I started developing the Verstappen closure. Almost none of the code is shared, which is why there are two files, unlike the Smagorinsky closures which have a lot of shared code. In principle it might be possible to refactor both implementations to share (a bit) more code but that would be a lot of work, and would also probably make both implementations more complex...

Didn't realize they were that different. In that case, maybe makes more sense to keep two separate files. More complex implementation of AMD sounds like a bad idea.

**Comment by glwagner** [comment]
> Didn't realize they were that different.

The difference between them is that both derivatives and velocity fields are normalized by Verstappen, while only derivatives are normalized by Rozema. To implement the Verstappen functions, I redefined functions that compute velocity gradients and tracer gradients by prefixing them with `norm_`. In the Rozema version, the normalization of derivatives is easily factored out by dividing the largest expression (for 27 terms) into 3 parts, so I don't need special operators and just use ordinary velocity gradient operators there.

**Comment by glwagner** [comment]
@ali-ramadhan probably a good idea to have a quick glance through 

https://github.com/climate-machine/Oceananigans.jl/blob/be136c306530c947d45a28bf762e3f5f376a6802/src/turbulence_closures/verstappen_anisotropic_minimum_dissipation.jl

to see what I am talking about.

**Comment by glwagner** [comment]
@ali-ramadhan feel free to hit the red button when you are ready.

**Pull request merged**
