### PR TITLE
Checks if BC arrays are CuArrays

### LINKED ISSUE #419: Check boundary condition arrays are CuArrays if arch=GPU
The code segfaults otherwise.

### PR DESCRIPTION
**Pull request by suyashbire1**
Resolves #419

Thanks @ali-ramadhan

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Awesome! Seems like a good idea to check for this as otherwise the resulting segfault gives no indication about what to debug.

Some ideas to improve this PR:
1. Right now you only iterate over the values of the named tuple `boundary_conditions`. If you also iterate over the keys, then when the warning is printed you can also say exactly which boundary condition is the problem which might help the user.
2. Might also be good to check the opposite case: when `arch == CPU()` but one of the boundary conditions is a `CuArray`.
3. Would be good to have a test for this functionality. `@test_throws` can check that the Model constructor throws the expected error when running on the GPU with an `Array` and vice versa.

We might also want to implement a similar function to check that all float types in a model are consistent, i.e. to avoid running with `Float32` fields and a `Float64` equation of state.

**Comment by ali-ramadhan** [comment]
Also a design choice to be made:

When we notice the user has given the wrong inputs do we
1. Tell the user what went wrong and how to fix it so at the scripts are correct/robust, or
2. Fix as much as possible behind the scenes so the input can be quite flexible and things just work™.

Both seem to have advantages/disadvantages. Just curious what others think.

**Comment by glwagner** [comment]
Interesting. Should *any* fields be arrays? Can we use has_reference?

**Comment by suyashbire1** [comment]
> Should any fields be arrays? 

Is there a better way to specify a boundary condition that has a fairly complex variation in space? I guess a function could be used? But I did not come across a template for a function like that (May be we could write a template that others can use).

> Can we use has_reference?

The way I understand it, has_reference will only check if at least one field is a CuArray. We need to check for each one of them here. I might be wrong.

**Comment by glwagner** [comment]
Hmm, I was thinking that there would be two conditions for an error:

1. Arch is GPU and one of velocities, tracers. pressures, poisson solvers, forcing, diffusivities, boundary conditions contains a reference to an Array (so any([has_reference(CuArray, obj) for obj in obj_list]). 

2. vice versa — arch is CPU and any of those fields reference a CuArray

**Comment by ali-ramadhan** [comment]
Sounds like it would make sense to move `has_reference` to `utils.jl` and use it to implement this check.

**Comment by suyashbire1** [comment]
This one is just 6 lines of code. So I'm going to revisit this later. Also, this issue is not a priority because I'm now using functions instead of arrays for boundary conditions. 

Closing this for now.

**Pull request closed without merging**
