### PR TITLE
[WIP] Integrate LES functionality

### PR DESCRIPTION
**Pull request by glwagner**
This PR starts the processes of integrating LES functionality from glwagner/pass-tests into Oceananigans master. It is very much WIP at the moment.

### CODE REVIEW

**Comment by glwagner** [comment]
@ali-ramadhan this PR is ready for a first review.

Possibly we should also add docs in this PR. I could also envision a few more tests to ensure the correctness of the turbulent diffusivities in simple flow fields for Constant Smagorinsky and Anisotropic Minimum Dissipation. However this last is not necessary.

**Comment by ali-ramadhan** [comment]
When we switch to finite volume operators (PR #283) it'll become much clearer where we are imposing no-flux and zero gradient conditions which should help along with comments like `# no penetration` and `# no-gradient condition`. We also switch from `▶` to `ϊ (\iota\ddot)` for interpolation but we can take care of these later. Would be good to have the turbulence closures using `Oceananigans.Operators` instead of redefining their own operators.

**Comment by ali-ramadhan** [comment]
> Possibly we should also add docs in this PR.

How much of it is similar with dedaLES documentation of turbulence closures? Might be mostly copy paste?

**Comment by ali-ramadhan** [comment]
Might be good to close #120 and release v0.9.0 once this PR is merged? Well, maybe release a new minor version once LES is verified.

**Comment by ali-ramadhan** [comment]
> I could also envision a few more tests to ensure the correctness of the turbulent diffusivities in simple flow fields for Constant Smagorinsky and Anisotropic Minimum Dissipation. However this last is not necessary.

Hmmm, wonder if it's worth doing this if we're going to do some more rigorous LES verification anyways? The rigorous tests probably won't pass initially which will lead us to do these simpler tests first maybe.

**Comment by christophernhill** [comment]
@ali-ramadhan and @glwagner is the incmod(), decmod() stuff the right thing to do in this. I am trying to think how this will interact with Halo() code elsewhere? Would we be better off filling halos at various intermediate stages for now. We can then tidy up and use wiser halos later? Any thoughts?

**Comment by ali-ramadhan** [comment]
> @ali-ramadhan and @glwagner is the incmod(), decmod() stuff the right thing to do in this. I am trying to think how this will interact with Halo() code elsewhere? Would we be better off filling halos at various intermediate stages for now. We can then tidy up and use wiser halos later? Any thoughts?

Not sure if this is the final form of this PR, but I suggested we just merge the closures as is, with operators that use `incmod1` and `decmod1`, mostly to integrate the closures ASAP. It's definitely a little inconsistent with the rest of the fields that use halos.

We could focus on cleanup of this kind once we verify that the LES closures work, unless this is a pretty urgent issue.

**Comment by christophernhill** [comment]
@ali-ramadhan OK. I guess I am missing whether the LES can work with incmod at same time as structures are haloed?  e.g  in below, unless ```u``` is some sort of view (?), it looks slightly wrong to me if ```u[1]``` (for example) is in a halo? 

```
@inline function ∂x_caa(i, j, k, grid, u::AbstractArray)
    i⁺ = incmod1(i, grid.Nx)
    return @inbounds (u[i⁺, j, k] - u[i, j, k]) / grid.Δx
end
```

**Comment by ali-ramadhan** [comment]
I think they should as the `incmod1` operators should do the exact same job as the halos (assuming periodic boundary conditions), but might also be missing something.

**Comment by glwagner** [comment]
> How much of it is similar with dedaLES documentation of turbulence closures? Might be mostly copy paste?

Math is the same, but docs syntax is different.

**Comment by glwagner** [comment]
@christophernhill @ali-ramadhan using `incmod1` will probably work for periodic domains, as it is equivalent to ignoring the existence of halos. 

Using `incmod1` does defeat the work done to implement side wall boundary conditions.

**Comment by christophernhill** [comment]
Ok - got it!

**Comment by ali-ramadhan** [comment]
@glwagner Sounds like this is ready to be merged?

**Comment by glwagner** [comment]
@ali-ramadhan I think so! Docs will come in a subsequent PR.

**Pull request merged**
