### PR TITLE
More fixes in docs

### PR DESCRIPTION
**Pull request by glwagner**
This PR completes @navidcy contributions in #111 .

### CODE REVIEW

**Comment by glwagner** [comment]
Phew. @ali-ramadhan feel free to merge when you see fit.

**Comment by ali-ramadhan** [comment]
Not sure what was wrong with your last PR #112 but looks good!

Did you check if moving all the `\newcommand`s to the top in a math block works with Documenter? @navidcy and I both could not get it to work (https://github.com/climate-machine/Oceananigans.jl/pull/111#issuecomment-470516584 and https://github.com/climate-machine/Oceananigans.jl/pull/111#issuecomment-470527180).

**Comment by glwagner** [comment]
> Did you check if moving all the \newcommands to the top in a math block works with Documenter?

It worked in my local build (once I fixed syntax errors).

**Comment by ali-ramadhan** [comment]
Ah maybe it was just syntax errors. Let's merge and find out!

**Pull request merged**
