### PR TITLE
Asynchronous NetCDF output.

### LINKED ISSUE #124: Asynchronous output writing.
So time stepping can continue (especially on the GPU) while the CPU writes and compresses output.

See:
* https://docs.julialang.org/en/v1/manual/parallel-computing/index.html
* https://stackoverflow.com/questions/37287020/how-and-when-to-use-async-and-sync-in-julia

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR adds an option `async::Bool` to the `NetCDFOutputWriter`. By default `async=false`. When `async=true` the data to be written to disk is copied and is asynchronously written to disk  by a second worker/process. This is especially useful when running models on the GPU as writing and compressing NetCDF output is time consuming and the GPU is just idle while this is happening.

In particular, compressing NetCDF seems to be very inefficient. It takes way too long. I'm considering setting `compress=0` or trying out NCDatasets.jl. We can also just write output to JLD then convert all the JLD files to one big NetCDF after the model is done time stepping.

See the free convection example to see this feature in action.

I tried to keep all the parallel computing stuff under the hood but unfortunately I could not get this feature to work without manually calling `addprocs()` and `@everywhere using Oceananigans` in the example, so for now it requires some work on the user's part.

cc: @SandreOuza 

Resolves #124.

### CODE REVIEW

**Comment by glwagner** [comment]
+1 for NCDatasets.

Asynchronous output writing is great; we will also want this (or at least a similar concept) for high-frequency diagnostics gathering + occasional writing of gathered diagnostics. 

I'll open an issue later today once I hammer out the requirements for this functionality.

**Comment by ali-ramadhan** [comment]
It's pretty bad. I don't think the compression level functionality even does anything!

```julia
using NetCDF
N = 256^3
A = rand(N)

for cl in 0:9
    tic = time_ns()
    
    filename = "compress" * string(cl) * ".nc"
    varname  = "rands"
    attribs  = Dict("units"   => "m/s")

    nccreate(filename, varname, "x1", collect(1:N), Dict("units"=>"m"), atts=attribs, compress=cl)
    ncwrite(A, filename, varname)
    ncclose(filename)
    
    toc = time_ns()
    
    ts = prettytime(toc - tic)
    fs = datasize(filesize(filename); style=:bin, format="%.3f")
    println("Compression level $cl: $ts $fs")
end
```

```
Compression level 0: 4.784 s 233.989 MiB
Compression level 1: 4.618 s 233.989 MiB
Compression level 2: 4.358 s 233.989 MiB
Compression level 3: 5.900 s 233.989 MiB
Compression level 4: 4.456 s 233.989 MiB
Compression level 5: 4.643 s 233.989 MiB
Compression level 6: 4.353 s 233.989 MiB
Compression level 7: 5.022 s 233.989 MiB
Compression level 8: 6.425 s 233.989 MiB
Compression level 9: 4.271 s 233.989 MiB

```

Either way I need to figure out why CI is crapping out. Might be the use of the Distributed package.

**Comment by ali-ramadhan** [comment]
PS: @glwagner we already have https://github.com/climate-machine/Oceananigans.jl/issues/31 open to discuss NetCDF output.

If you open a new issue we should close #31.

**Comment by ali-ramadhan** [comment]
Tests are passing so I will merge unless there are any objections.

Code coverage decreased but I'm not sure how to test this as it would require spinning up another worker on CI (not available to us as we're on the free-tier CI plans).

**Pull request merged**
