### PR TITLE
Consolidates timestepping-related fields into struct

### PR DESCRIPTION
**Pull request by glwagner**
This PR consolidates all timestepper-related fields into a struct called `AdamsBashforthTimestepper`.

This change is also necessary to eventually support multiple time steppers, though this is far in the future.

The Adams-Bashforth parameter can now be set in the model constructor.

cc @jm-c

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Looks great!

My only comments would be about the filenames:
* `kernels.jl` sounds a little vague. Would `time_stepping_kernels.jl` be better?
* Not sure what the Julia convention is but I think having underscores between words in filenames improves readability: e.g. `time_steppers.jl` instead of `timesteppers.jl`.

**Comment by glwagner** [comment]
Julia used to recommend somewhere in the documentation that one should only use underscores when necessary (and many of the core julia functions reflect this style). I guess I felt that `timesteppers` is clear and readable. I'm fine if you change it though. It would be more consistent with the rest of the code anyways (for example, the function `time_step!`.

**Comment by glwagner** [comment]
@jm-c recommends that we shelve this PR by the way until we deal with other stuff. The changes in this PR affect many of the other PRs.

**Comment by ali-ramadhan** [comment]
Ah fair enough, we can prioritize the PRs.

**Comment by glwagner** [comment]
Let's close this --- the code will change a lot soon and we can easily rewrite these changes.

**Pull request closed without merging**
