### PR TITLE
Minor code simplifications

### PR DESCRIPTION
**Pull request by glwagner**
This PR does some minor refactoring to reduce code length. It also introduces an `AdamsBashforthTimestepper` type which will be useful in the future if new timesteppers are implemented.

@ali-ramadhan, can you check to see that GPU tests pass? I had some trouble on my local machine.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
If GPU tests are failing it might be the channel tracer conservation GPU test as assigning a number to a CuArray slice via broadcasting seems to have stopped working.

I asked about it on Julia Slack, waiting to see if it's actually a bug.

**Comment by ali-ramadhan** [comment]
Generally looks fine. Some nice clean up!

It seems you're gravitating towards having fewer files which I think is a bad idea. Having more modular files helps a lot with both readability and organization, especially for someone who's looking through the code for the first time. It also becomes harder to find stuff with longer files.

For example, It's not logically clear to me that forcings and field sets should be in `models.jl`. And if I'm looking through the file for the first time, I might find it hard to comprehend all the different functionalities provided in the file.

Unrelated to this PR but working on the checkpointer in `output_writers.jl` the file has become a long list of functions, some of which are shared between multiple output writers so I think it makes more sense to split it into a set of shared functions and a file for each output writer.

**Comment by glwagner** [comment]
My reasoning was that the functions VelocityFields, TracerFields, and PressureFields seem to provide a minor convenience and are only called from the model constructor (in principle one could simply build named tuples of velocity fields, tracers, pressures directly in the constructor without intervening functions). Thus it seems nice for these functions to live close to the model constructor where they can be understood while reading the model constructor code. That is my main motivation for coalescing what would have remained from fieldsets.jl into models.jl. 

As for forcing, it’s just one/two lines, so it didn’t seem right to have a separate file. Ultimately this is a temporary implementation. We will need a more sophisticated way to build tuples or forcing functions when we have arbitrary tracers. 

I don’t immediately see why putting those functions in separate files is helpful for readability, since I find it hard to read code that is spread across many small files. But I’m open to putting them back if my views are idiosyncratic.

**Comment by glwagner** [comment]
By the way, another aspect of having an AdamsBashforthTimestepper is that the Adams bashforth parameter “χ” can now be set.

**Comment by ali-ramadhan** [comment]
Sorry I didn't mean to criticize this PR, it was more of a general comment. I agree that `fieldsets.jl` and `forcings.jl` will be refactored at some point in the near future.

This PR seems ready to be merged if you want to do it. Still waiting to hear from the Julia Slack if CuArrays has a bug.

> I don’t immediately see why putting those functions in separate files is helpful for readability, since I find it hard to read code that is spread across many small files. But I’m open to putting them back if my views are idiosyncratic.

I think it's more about organization, especially for newcomers. We're pretty familiar with the code so we don't need files to be as neat or organized. But to a newcomer, a code base with a few long/dense files is much harder to understand, it's especially hard to figure out where to find stuff. Having more modular files would make it easier to see what Oceananigans offers and what parts are under the hood.

I'm happy working with small or large files, just thinking what might be best for users or potential collaborators.

**Comment by glwagner** [comment]
Ok, let's merge this and continue the conversation about code organization in future PRs.

**Pull request merged**
