### PR TITLE
Robust setting of fields

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Just combining my commits from PRs #337 and #341.

Idea is to make life more comfortable by getting `set!` to work out of the box for CPU and GPU fields, and for setting them with functions or arrays.

The functions should be evaluated on the CPU as not every function is available through CUDAnative (notably `rand` and `randn` are missing).

Will switch to using `copyto!`.

### CODE REVIEW

**Comment by glwagner** [comment]
@ali-ramadhan please see my contribution.

I believe the following combinations are now supported

* number data with CPU and GPU fields
* data from alike fields for CPUs and GPUs
* CPU fields to GPU fields (using `copyto!`)
* CPU arrays to CPU fields
* CPU arrays to GPU fields (by forming a CPU field and then using `set!` for CPU fields to GPU fields)
* GPU arrays to GPU fields (using the kernel `_set_gpu!`)
* GPU fields to CPU fields (via array conversion of `.data.parent`)
* functions to CPU fields (using `nodes(u)...`)
* function to GPU fields (by computing the CPU field and then using `set!` for CPU fields to GPU fields)

I have also added a docstring for `set!(model; kwargs...)` with an example, and a simple test.

(I also nuked `EdgeField`).

Hopefully that is comprehensive enough for now. Please let me know if anything more should be added.

**Comment by ali-ramadhan** [comment]
Awesome stuff! Should make scripting life much more comfortable. We should release v0.9.3 once this is merged.

GPU tests don't start due to this error. Will see if I can fix it.
```julia
ERROR: LoadError: LoadError: UndefVarError: T1 not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /builds/JuliaGPU/Oceananigans-jl/src/Oceananigans.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:328 [inlined]
 [12] eval(::Expr) at ./client.jl:404
 [13] top-level scope at ./none:3
in expression starting at /builds/JuliaGPU/Oceananigans-jl/src/fields.jl:188
in expression starting at /builds/JuliaGPU/Oceananigans-jl/src/Oceananigans.jl:204
```

**Comment by ali-ramadhan** [comment]
Tests run but 4 of the `set!` tests are failing on GPU now.

**Comment by glwagner** [comment]
@ali-ramadhan ok thank you! I’ll look into the GPU stuff and let you know when it’s fixed.

**Comment by ali-ramadhan** [comment]
Ended up being a simple issue where
```julia
set!(u::Field{A1}, f::Function) where {A1 <: OffsetArray{T, D, <:CuArray} where {T, D}}
```
assumed `u_cpu` was always a `CellField`.

Tests should pass now.

Let me know if this makes sense but I also moved your `set_velocity_tracer_fields` test to `test_models.jl` as it constructs a model, but we don't know if `model()` actually works until we test it in `test_models.jl`.

So now we test `set!` after `model()` has been tested.

**Comment by ali-ramadhan** [comment]
Hmmm, GitLab didn't run for some reason so I ran the tests on Google Cloud and everything passes now.

```
Test Summary: | Pass  Broken  Total
Oceananigans  | 1261       7   1268
   Testing Oceananigans tests passed 
```

**Comment by glwagner** [comment]
Ok, great! Your logic for where the test should be run makes sense to me. 

I think your change to set! has rendered the fieldtype function unnecessary. Can we delete that so we don’t have floating code?

We also need to make sure the deepening_mixed_layer example runs (should we add a test that runs it somehow?). Then I’m happy to merge.

**Comment by ali-ramadhan** [comment]
Oh lol, didn't even realize we already coded up a `fieldtype` function. I'll make a commit cleaning that up.

It's used in a lot of places so sounds like we should redefine it to be
```julia
fieldtype(f::Field) = typeof(u).name.wrapper
```
and change `field_type = typeof(u).name.wrapper` to `field_type = fieldtype(u)`.

For the deepening mixed layer example, sounds like we just need to test that the model setup works in which it should go in `test_models.jl`? If it's going to be time stepped, then that's either a dynamics test or a regression test.

**Comment by ali-ramadhan** [comment]
Looks like all tests are passing. @glwagner do you want to merge this or still want to add a test for deepening mixed layer?

**Comment by glwagner** [comment]
@ali-ramadhan I will update the example and add a test.

**Comment by glwagner** [comment]
@ali-ramadhan check it out.

**Comment by ali-ramadhan** [comment]
@glwagner How long does the example test take? Travis CI is timing out:

```
    Running example deepening_mixed_layer.jl

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by glwagner** [comment]
@ali-ramadhan it does seem the example takes too long! I will reduce the resolution and also the duration of the simulation.

**Comment by glwagner** [comment]
@ali-ramadhan for the future I think we need to figure out a good pattern for writing examples in which the resolution/run time can be decreased for the purpose of testing.

**Comment by ali-ramadhan** [comment]
True. Yeah if it's not checking output or model state then 1 time step should be enough.

A hack could be that the test actually rewrites the file contents before running the example changing `time_step!(model, Nt, dt)` to `time_step!(model, 1, dt)` or something.

**Comment by ali-ramadhan** [comment]
Looks like in it's current form it spends ~35 seconds on time stepping on Appveyor. It also prints out a bunch of progress statements.

**Comment by glwagner** [comment]
@ali-ramadhan tests failed again so I give up. I'm skipping the example-running test for now. When the tests pass feel free to merge.

**Pull request merged**
