### PR TITLE
Be more concrete

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Reopening a PR based on #261 and #263 which I reverted as it broke some of the examples we usually run, e.g. free convection.

Before merging we should probably either refactor the examples to use the new boundary conditions API or come up with this `BoundaryConditionsWizard` that does everything for us.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
> Do these changes mean that we need to rewrite the PR that makes things more concrete? It looks like there will be a lot of merge conflicts.
> 
> _Originally posted by @glwagner in https://github.com/climate-machine/Oceananigans.jl/pull/290#issuecomment-506888727_

Looks like there will be a few conflicts but mostly small changes to the boundary conditions will need to be made. They're still mutable structs in this PR so a lot of the examples should still work.

I think the two big issues with this PR are still the same:
1. The way we set boundary conditions changes a little bit in this PR so we should probably also update any existing examples and scripts.
2. This PR breaks checkpointing. This is fine as long as we have a fix ready to merge. Been meaning to convert to a native Julia checkpointer that only saves the bare essentials to disk (either in binary or JLD2) so this is a good opportunity.

**Comment by glwagner** [comment]
I think we should let the checkpointing functionality lapse and return to it later, rather than keeping this important PR on hold until we solve that difficult problem.

**Comment by ali-ramadhan** [comment]
The checkpointing is important for long simulations like the seasonal cycles we've been running.

I'm okay with merging this soon as long as checkpointing becomes a priority afterwards.

It's not a difficult problem. You just pick the dozen or so fields that you need to checkpoint, save them, and have a `pickup` or `restore` function that reads the fields from disk and initializes a new model.

**Comment by glwagner** [comment]
Looks like the examples all work. What needs to be updated?

**Comment by ali-ramadhan** [comment]
I'll nuke checkpointing for now, resolve the merge conflicts, and merge this in.

**Comment by ali-ramadhan** [comment]
Not sure why GitLab CI pipeline isn't running on this PR (maybe because it's from a fork?) but the GPU tests pass on Engaging so I'll merge this PR once Travis and Appveyor pass as well.

**Pull request merged**
