### PR TITLE
More convenient BoundaryFunction functionality

### PR DESCRIPTION
**Pull request by glwagner**
This PR makes it a bit easier to prescribe `BoundaryFunction`s by providing field-specific constructors. The field-specific constructors "know" about the locations of tracers and velocity fields and relieve the user of the (often confusing) task of specifying the `BoundaryFunction` location.
I also added a further wrapper around `BoundaryCondition` to permit patterns like

```julia
northern_velocity(x, z, t) = cos((x - sin(t)))
u_bcs = UVelocityBoundaryConditions(grid, north=UVelocityBoundaryCondition(Value, :y, northern_velocity))
```

It doesn't look perfect to me, but I do think it's progress over what the user had to do previously.

A potential source of confusion (?) is that `UVelocityBoundaryCondition` is only needed for simple boundary functions. We could alleviate this with more verbosity; eg `UVelocityFunctionBoundaryCondition` or something silly like that. But I'm hesitant because we already seem to have a verbosity problem. We need better design, not more words...

I've also added a `parameters` field to `BoundaryFunction`.

(It only just occurs to me that perhaps what we want are types like `Tracer()`, `U()`, `V()`, and `W()`. We might use these to classify boundary conditions and forcing functions... ?)

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Since this is a breaking change (?) do you want to bump to version 0.27.0 in this PR?

**Comment by glwagner** [comment]
> Since this is a breaking change (?) do you want to bump to version 0.27.0 in this PR?

Will do.

**Comment by glwagner** [comment]
Ready to merge.

**Comment by glwagner** [comment]
> Since this is a breaking change (?) do you want to bump to version 0.27.0 in this PR?

Ah, it isn't a breaking change btw (it just adds a wrapper for existing functionality) --- but it does add a new feature, so 0.27.0 could still be warranted.

**Pull request merged**
