### PR TITLE
Rayleigh-Benard regression test with forcing and passive tracer

### PR DESCRIPTION
**Pull request by glwagner**
This PR introduces a new regression test (and renames "golden master tests" to "regression tests") based on Rayleigh-Benard convection that adds regression tests for `Value` boundary conditions, the forcing implementation and the salinity equation, by using salinity as a passive tracer in the test.

The test avoids setting random initial conditions by loading both the initial model state and the comparison state from file.

Note that loading the model state from file required writing a new `OutputWriter` that outputs and loads the "source terms", `G`. This implementation is included in `test_regression.jl`, but it may be worthwhile to integrate it into `output_writers.jl` at some point.

The test runs on the CPU and GPU. However, similar to the thermal bubble tests, this test fails on the GPU.

This PR also adds a file to `sandbox` to aid running and exploring solutions to Rayleigh-Benard and also demonstrates the user-specification of a forcing term.

### CODE REVIEW

**Comment by glwagner** [comment]
Note: I discovered a bug in the specification of the 'model configuration' (the viscosity and diffusivity coefficients were swapped). This bug does not affect the other regression tests or dynamics tests (which assume equal viscosities and diffusivities), but it does affect this regression test.

**Comment by glwagner** [comment]
#241 should be merged first. Then we will merge those changes here, and update the regression tests.

**Comment by glwagner** [comment]
I've merged in the fixed `Model` constructor and updated the regression test. This PR is now ready to merge, after #241 is merged. 

The bug that is fixed by #241 reveals that the different viscous and diffusive coefficients is an additional feature of this test.

It also suggests that in the future we should make sure to test as many features (as possible) in individual regression tests.

**Comment by ali-ramadhan** [comment]
Awesome! Good to have another test and a JLD output writer.

In light of #242 and #238, might be good to first figure out why the GPU golden master test fails for the thermal bubble test and fixing that before we merge this PR.

Out of curiousity, why the "golden master" -> "regression" name change?

**Comment by glwagner** [comment]
I changed the name because I believe that "golden master" is misleading: as far as I know, a "golden master" test is one in which the output of the model matches some *externally* verified result (eg, an MITgcm solution, or a numerical solution reported in the literature).

In other words, a "golden master" in our case is another numerical model that we (arbitrarily) deem to be a master.

These tests are not "golden master" tests in that sense. Instead, they test whether the output of the model has "regressed" (changed relative to prior output).

Basically, we should not be committing "updates" to a golden master test, because the golden master is... the golden master. However, we do have to update the regression test data when we find bugs in `Oceananigans`.

Make sense?

It would be nice to have golden master tests, too. Our best hope for this are tests that use a turbulence closure, since there are many published results for "low-resolution" solutions using common turbulence closures like Constant Smagorinsky. Unfortunately, we do not support the boundary conditions that the majority of published results use at low-resolution (either triply-periodic, or vertically-bounded with a 'wall model').

**Comment by glwagner** [comment]
I don't see the reason for waiting to merge this PR before fixing the GPU issue. This is a perfectly valid regression test; CPU tests pass using the output generated by the CPU, and the regression test itself is independent of the GPU issues. When the GPU solver is fixed, the GPU tests should pass for *both* thermal bubble *and* Rayleigh-Benard. It is nice that this test demonstrates consistent behavior with thermal bubble, as well.

I think #242 is a good reason to merge this test. This test further closes the gap between CPU and GPU tests. 

It should actually be useful to have these tests in place for fixing the GPU issue, because this regression tests stresses more features than the thermal bubble test.

**Comment by glwagner** [comment]
Note: this PR does not touch the algorithm. It only adds a test.

Also note that the major component that is different between the CPU and GPU is the poisson solver, and the poisson solver functionality is untouched by both #241 and this PR.

**Comment by ali-ramadhan** [comment]
That makes sense. I didn't realize the difference between a "golden master" and a "regression" test. I wouldn't call the output we produce right now to be "golden master" level.

As for merging this PR, I'm working on figuring out why the thermal bubble regression test fails on the GPU on the `fix-gpu-gm` branch. Hopefully it'll be something trivial. I'm thinking it's good to tackle one small problem at a time, and I'm more familiar with the thermal bubble test. The two regression tests may be failing for different reasons.

**Comment by glwagner** [comment]
> That makes sense. I didn't realize the difference between a "golden master" and a "regression" test. I wouldn't call the output we produce right now to be "golden master" level.

That's just how I'm defining it.

> The two regression tests may be failing for different reasons.

I don't understand your argument. This PR introduces a *test* --- it does not change the functionality of the code. If you merge these changes, you may find that once you resolve whatever issue the GPU solver has that *both* tests pass (and you can move on with your life). This will save you some work and time with zero risk of negative consequences.

**Comment by ali-ramadhan** [comment]
The thermal bubble regression test works on the GPU again (i.e. CPU and GPU output match).

Pretty sure the Rayleigh-Benard GPU regression test will pass now, so probably good to merge after #243.

**Comment by ali-ramadhan** [comment]
On another note, the deep convection regression test is disabled right now as it's waiting for a truly portable random number generator #219 but maybe a better approach is to just save the initial condition to disk like you did here.

**Comment by glwagner** [comment]
You should merge this before #243.

**Comment by ali-ramadhan** [comment]
Ah right, that makes more sense.

**Pull request merged**
