### PR TITLE
[WIP] A new boundary condition API

### PR DESCRIPTION
**Pull request by glwagner**
This PR implements a new boundary condition API.

It's a bit of a work in progress. Before merging we need:
* tests (simple 1D test with temperature to see if budgets are correct?)
* export some appropriate objects / functions to user
* some API development to make boundary condition specification easier
* documentation.

Criticism welcome!

## Summary of implementation: the `BoundaryCondition`

The core type of this PR is `BoundaryCondition`. The `BoundaryCondition` has one field, `calc`, and is made callable via

```julia
(bc::BoundaryCondition)(args...) = bc.calc(args...)
```

A `BoundaryCondition` has one parameter: `BCType`. The `BCType` can be `Default`, `Flux`, or `Value`. We include `Default` because the specification of boundary conditions is baked in to the algorithm. In the case of 'default' boundary conditions, no calculations are made.

### `nboundary_conditions = nfields x ndims x 2`.

In principle, the user can specify `5 x 3 x 2` boundary conditions: on each of the 5 fields (which we currently have --- unfortunately, we may want more in the future), the user can specify a condition on any of the 6 boundaries. The model is initialized with all 30 boundary conditions set to `Default`.

We allow for all possible boundaries to have conditions by introducing three structs:

* `CoordinateBoundaryConditions` with fields `left` and `right`
* `FieldBoundaryConditions` with fields `x`, `y`, and `z`
* `BoundaryConditions` with fields `u`, `v`, `w`, `T`, and `S`.

### Specifying boundary conditions and user API

A boundary condition is now specified by defining a function that calculates it within a kernel that loops over the boundary in question. The arguments of a flux boundary conditions on a top or bottom boundary (the only situation supported so far) are

```julia
u, v, w, T, S, t, step, Nx, Ny, Nz, Δx, Δy, Δz, i, j
```

This will probably change in the future.

The user API is rather threadbare at the moment. To define a constant flux boundary condition, for example, the user might write (to specify the boundary condition as a function)

```julia
model = Model(...)

const constant_flux = # something
surface_temperature_flux(args...) = constant_flux
flux_bc = BoundaryCondition{Flux}(surface_temperature_flux)
model.boundary_conditions.T.z.right = flux_bc
```

to specify the boundary condition as a constant, 

```julia
model = Model(...)

flux_bc = BoundaryCondition(Flux, constant_flux)
model.boundary_conditions.T.z.right = flux_bc
```

There are probably some sugary things that we can implement to smooth this specification.

### Caveats

* We support only flux boundary conditions at top and bottom at the moment
* We can only handle fluxes in terms of the constant vertical viscosities and diffusivities
* If the viscosities and diffusivities are allowed to vary in the vertical at some point in the future, we will have to re-configure the implementation
* We cannot intercept the specification of a flux if we have, for example, a parameterization like KPP that takes care of the surface fluxes with a closure (rather than as a boundary condition).

### A side note

I think that, at some point, it would be preferable to move the implementation of boundary conditions and equations to a new file / module so that new physics can be easily implemented my modifying that module / file.

### CODE REVIEW

**Comment by glwagner** [comment]
@ali-ramadhan @jm-c I realized that I may have specified the flux boundary condition wrong --- I think that I am double counting the flux coming in/out of the cell from the interior (this part is calculated during the main time-stepping loop. I guess the sanity check is that it shouldn't do anything if `flux` is zero.

I'll add you as collaborators on my repo in case you want to change anything (I probably won't have time till Monday). Also looks like Travis is failing; not sure why that is.

Feel free to criticize my design. This is just a first pass as I see it.

**Comment by glwagner** [comment]
I propose changing the struct `BoundaryConditions` to `ModelBoundaryConditions` for clarity.

**Comment by ali-ramadhan** [comment]
Thanks for embarking on this @glwagner!

> It's a bit of a work in progress. Before merging we need:
> * tests (simple 1D test with temperature to see if budgets are correct?)

Just added "WIP" (work in progress) to the PR title.

We can work on the tests together. For testing, we should be able to extend the 1D column model example: https://github.com/climate-machine/Oceananigans.jl/blob/master/examples/column_model.jl

> Also looks like Travis is failing; not sure why that is.

Looks like it's just the one test in the time stepping section that's failing. Maybe something to do with how the boundary conditions are called during the time stepping? The Model test passes so it's not erroring during model initialization/construction.

> I propose changing the struct `BoundaryConditions` to `ModelBoundaryConditions` for clarity.

I'll always vote for clarity!

Just one initial question: I might be misunderstanding the purpose of `bc.calc` but why not `bc.impose(args...)` instead of `bc.calc(args...)` as we usually say that we _impose_ boundary conditions?

Have to run out but will have a more detailed look later today.

**Comment by ali-ramadhan** [comment]
Just another thought. If it's implemented in this way with
* `CoordinateBoundaryConditions` on the `left` and `right` parts of the domain.
* `FieldBoundaryConditions` along the `x`, `y`, and `z` dimensions.
* `BoundaryConditions` on the `u`, `v`, `w`, `T`, and `S` fields.

with the final boundary condition being a function, would there be 30+ nested parameterized types for `ModelBoundaryConditions`. Is/should that be a concern?

**Comment by johncmarshall54** [comment]
It's not obvious to me what a _field_ boundary condition is, vs a _coordinate_ boundary condition. 
Fundamentally we are applying boundary conditions to u, v, w, T, and S fields, and that's it.  It all seems a bit too complicated.

**Comment by glwagner** [comment]
@johncmarshall54 each field (`u`, `v`, `w`, `T`, `S`) can have boundary conditions in each direction (`x`, `y`, `z`). 

We could restrict ourselves to specific combinations of boundary conditions instead, which would reduce the number of possibilities. For example, we might have just doubly periodic in (`x`, `y`) plus flux in `z` on all fields, or singly-periodic in `x` and flux in (`y`, `z`) on all fields.

The current design is meant to give the user maximum flexibility, but I'm open to simplifying it. That would restrict what users can do, but perhaps that's ok?

@jm-c feedback welcome!

**Comment by glwagner** [comment]
> would there be 30+ nested parameterized types for ModelBoundaryConditions. Is/should that be a concern?

@ali-ramadhan do you mean with regards to performance? I'm not sure. With multiple dispatch being core to julia it seems this scenario is not uncommon (30+ may not be very large).

> Just one initial question: I might be misunderstanding the purpose of bc.calc but why not bc.impose(args...) instead of bc.calc(args...) as we usually say that we impose boundary conditions?

The function `calc` does not actually impose a boundary condition --- the imposition of boundary condition depends on, for example, the viscosity and diffusivity, and is a property of the equation (or turbulent closure) being implemented. Again for example, the K-Profile-Parameterization includes a modification of how a flux boundary condition is implemented. In other words, the "specification of flux" is separate from the "imposition of a boundary condition". The former is determined by the user. The latter is determined by the model/governing equation.

**Comment by glwagner** [comment]
It should be noted that this PR also makes progress on addressing #100.

**Comment by ali-ramadhan** [comment]
> We could restrict ourselves to specific combinations of boundary conditions instead, which would reduce the number of possibilities. For example, we might have just doubly periodic in (x, y) plus flux in z on all fields, or singly-periodic in x and flux in (y, z) on all fields.

Agree that `CoordinateBoundaryConditions` might be a weird name but yeah, maximum flexibility would be very powerful. Maybe the common use case isn't to impose each of the 30 boundary conditions one-by-one but we can just have nice helper functions/abstractions like
 ```julia
model.boundary conditions += HorizontallyPeriodic()
```

> @ali-ramadhan do you mean with regards to performance? I'm not sure. With multiple dispatch being core to julia it seems this scenario is not uncommon (30+ may not be very large).

I'm still pretty new to Julia so yeah don't know if that will be an issue, especially on the GPU. Only way to find out is to try and benchmark! Maybe you're right and 30+ isn't a lot.

@vchuravy any idea on whether 30+ parameterized types for a struct is too many? Would this hurt performance on the GPU?

> The function calc does not actually impose a boundary condition --- the imposition of boundary condition depends on, for example, the viscosity and diffusivity, and is a property of the equation (or turbulent closure) being implemented. Again for example, the K-Profile-Parameterization includes a modification of how a flux boundary condition is implemented. In other words, the "specification of flux" is separate from the "imposition of a boundary condition". The former is determined by the user. The latter is determined by the model/governing equation.

I see. So if no parameterizations are being used, are the boundary conditions actually being _imposed_ then? Even with KPP, isn't the boundary condition still being _imposed_ only to later be modified by KPP?

I still feel like `bc.calc()` feels obscure, I'm not sure why a boundary condition should have to calculated. Perhaps it's just semantics but it would be nice to see boundary conditions be _imposed_ in the code and see something like `bc.impose(...)`.

**Comment by glwagner** [comment]
> So if no parameterizations are being used, are the boundary conditions actually being imposed then?

I believe yes: if the viscosity/diffusivity is 0, then flux or no-slip boundary conditions cannot be imposed (mathematically, the order of the PDE is reduced in that case). We then can only impose no-penetration or periodic conditions.

> I still feel like bc.calc() feels obscure

My primitive logic: for a flux boundary condition, `bc.calc()` "calculates" the flux at the given grid point and time-step. For a "value" boundary condition, `bc.calc()` "calculates" the value of the boundary condition at the given grid point and time-step. But I agree it is a weird name. What is a better name?

**Comment by glwagner** [comment]
Other names:

* `bc.get`
* `bc.specification`
* ... ?

> Agree that CoordinateBoundaryConditions might be a weird name but yeah, maximum flexibility would be very powerful. Maybe the common use case isn't to impose each of the 30 boundary conditions one-by-one but we can just have nice helper functions/abstractions

precisely, and I like the syntax you propose. We can do lots of stuff here to make our user's lives easy.

There are two issues: the backend, and the user interface. Maybe the title of this PR is confusing, because I think it's primarily about the backend.

**Comment by ali-ramadhan** [comment]
> My primitive logic: for a flux boundary condition, bc.calc() "calculates" the flux at the given grid point and time-step. For a "value" boundary condition, bc.calc() "calculates" the value of the boundary condition at the given grid point and time-step. But I agree it is a weird name. What is a better name?

It may not stand up to mathematical rigor but I still like `bc.impose()`. In your two examples, I feel like a flux is being _imposed_ and a value is being _imposed_.

If `bc.calc()` calculates a number then it should be used as
```julia
something = bc.calc(args...)
```
while `bc.impose` should be used like
```julia
bc.impose!(args...)
```

But now we're just arguing semantics instead of what's important.

> There are two issues: the backend, and the user interface. Maybe the title of this PR is confusing, because I think it's primarily about the backend.

I think so too. API suggests more front-end.

I also think discussing these dense and complicated issues (e.g. this PR and #120) among multiple busy people is difficult on GitHub. Little far ahead but maybe the Monday CliMA meetings are a good place to get high-level feedback?

**Comment by glwagner** [comment]
Sure, we can talk about code design at the CliMa meeting.

Let me summarize what we've discussed so far:

## The current design

A "boundary condition" is a flux, gradient, or value of a field (`u`, `v`, `w`, `T`, `S`) at the end (`left`, `right`) in a given direction (`x`, `y`, `z`).

### Pros

* Generality: any boundary condition can be specified
* Similarity to the mathematics: this design corresponds to how boundary conditions are specified in PDEs
* Extensibility: the design accommodates changes in *types* of boundary conditions or changes in dimensionality. (Adding new solution variables requires code modification, but that is true throughout the code)

### Concerns

* It's more complicated than allowing only 3-4 possibilities to users; as @johncmarshall54 says:

> It's not obvious to me what a field boundary condition is, vs a coordinate boundary condition.
Fundamentally we are applying boundary conditions to u, v, w, T, and S fields, and that's it. It all seems a bit too complicated.

* The hierarchical dependence of this design on parameterized types creates a lot of possibilities for different boundary conditions to be specified, and this is a concern for performance (@ali-ramadhan)

* We aren't sure what to call the function (currently `bc.calc`) whose purpose is to return the value of the boundary condition (either the field value, flux, gradient, or whatever) at a given grid point and simulation time

### Other miscellaneous thoughts

* This PR implements a backend / abstraction system for specifying boundary conditions. For users we can add as much sugar on top as we want.

* As we have discussed, the way we implement boundary conditions is intimately connected to the way that we specify equations. This can be seen in the current code (though it is commented out) in that [the lines that specify a no-slip condition depend on the "vertical viscosity"](https://github.com/climate-machine/Oceananigans.jl/blob/7fb355d77df98e37a80b3e796291fa2856d3e1ce/src/time_steppers.jl#L293). Adding other diffusive terms (hyperdiffusivity, Leith diffusivity, various turbulent diffusivity parameterizations/closures) can affect how the boundary condition is implemented. We are not ready to develop an equation abstraction system yet, but we must keep in mind the difference between *implementing* a boundary condition in the context of a set of equations, and *specifying* a boundary condition. This PR attempts to solve the latter problem. 

* It would be nice to know how MITgcm implements different boundary conditions.

**Comment by glwagner** [comment]
@SandreOuza has requested a `Gradient` `BCType`.

Also here are some proposed tests:

0. Constant initial conditions + zero flux = average value of quantity doesn't change
1. Linear temperature profile + prescribed identical fluxes at top and bottom = linear temperature profile
2. Diffusive solution to the free-convection example

**Comment by christophernhill** [comment]
That sounds like a potentially nice abstraction. Can we get together
tomorrow to sync up on details?

Chris

**Comment by glwagner** [comment]
Ok, sounds good! I’m going to try to write some of those tests this morning.

**Pull request merged**
