### PR TITLE
Kinematic hydrostatic pressure and buoyancy

### PR DESCRIPTION
**Pull request by glwagner**
This PR updates the code to use kinematic (density normalized) hydrostatic pressure and buoyancy rather than density perturbation. Using kinematic pressure simplifies the code because the reference density no longer affects the algorithm. Using buoyancy instead of the density perturbation will ultimately simplify the code further because it is needed for turbulence closures (for example).

The docs should be updated before merging.

Also, the golden master tests should be updated elsewhere; then it can be confirmed here that these changes preserve the functioning of the code (these changes do not affect the outcome of the algorithm).

I have also copy/pasted an interpolation operator that will become part of the code once #234 is merged. Prior to this PR, the interpolation of the buoyancy field to z faces was done manually.

We need a function to calculate buoyancy for the turbulence closures; so I think we are better off deleting the density perturbation function, ultimately. After this change the reference density ceases to be used in the algorithm.

I have also included salinity in the calculation of buoyancy.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Looks good to me! Agree that it should just pass the golden master test.

Would also be good to get @jm-c's comments before merging.

**Comment by jm-c** [comment]
Hi there,
2 comments:
1) does not look like the most urgent thing in the to-do list so we could wait until
 we have discussion in person.
2) with realistic EOS, we will need to comute density to get the hydrostatic 
 pressure AND N^2 (as input of mixing/SGS closuse scheme). Can express
 everything as normalised by rho_c but could easily get confusing.

**Comment by glwagner** [comment]
We need a function to compute buoyancy for the turbulence closures. I chose to work on this for a reason.

**Comment by glwagner** [comment]
We need a function to compute buoyancy for the turbulence closures.

**Comment by glwagner** [comment]
I can hack in a function to compute buoyancy for the purposes of implementing the turbulence closures that we need in the very immediate future --- I was hoping that this would provide a more robust and permanent solution.

**Comment by ali-ramadhan** [comment]
We can have both a `δρ(eos, T, i, j, k)` and a `buoyancy(i, j, k, grid, eos, g, T, S)` function so why can't the `update_buoyancy!` function continue using `δρ` (and maybe `ρ` in the future) while the turbulence closures can use the new `buoyancy` function?

**Comment by glwagner** [comment]
@ali-ramadhan that will work. I just wanted to have the assurance that buoyancy was being computed identically everywhere (if tests that stress the buoyancy function pass, we know it works).

**Comment by ali-ramadhan** [comment]
Fair enough, that's a good point. Seems like motivation to implement a unit test for the `update_buoyancy!` function (so that it can be tested with `δρ` and `b`), although not sure what a good test would be...

**Comment by glwagner** [comment]
This isn't moving, so I'm closing it.

**Pull request closed without merging**
