### PR TITLE
Fix calculation of Value boundary conditions

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Should be `Δz^2` instead of `Δz`.

But this cannot be merged as is because it breaks some tests: the Rayleigh–Bénard tracer regression test uses Value boundary conditions and so the regression data would have to be regenerated.

### CODE REVIEW

**Comment by glwagner** [comment]
Let’s remake the data and get rid of the JLD dependence at the same time.

**Comment by glwagner** [comment]
@ali-ramadhan I've tidied up the regression test and remade the data. Let me know what you think.

**Comment by ali-ramadhan** [comment]
Looks good! The channel tracer conservation test is still failing but I've opened a CuArrays issue about it: https://github.com/JuliaGPU/CuArrays.jl/issues/386

**Comment by glwagner** [comment]
@ali-ramadhan, CuArrays issue may be fixed in #323.

**Comment by ali-ramadhan** [comment]
Hmmm, that PR just deleted files that weren't in use so it shouldn't have any affect.

Pretty sure it showed up with the new version of CuArrays which we upgraded to in commit aa601c7d2241eb0ef09438ec1cd779f836d82436

**Comment by glwagner** [comment]
@ali-ramadhan, #329 changes the code in the file in which the error occurs.

**Pull request merged**
