### PR TITLE
Kernel for setting initial conditions so set_ic! runs fast on GPUs

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR uses a GPUifyLoops kernel to set initial conditions so `set_ic!` runs fast on GPUs.

Should make life more comfortable.

cc @sandreza

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
This is more like it
```julia
model = Model(N=(256, 256, 256), L=(1, 1, 1), arch=GPU())
u₀(x, y, z) = x+y+z
v₀(x, y, z) = sin(x*y*z)
T₀(x, y, z) = tanh(x+y-z)
@time CuArrays.@sync set_ic!(model; u=u₀, v=v₀, T=T₀)
  0.058545 seconds (691 allocations: 127.984 KiB)
```

Might just have to be careful as we can't pass in functions that rely on stuff not defined in CUDAnative (GPUifyLoops won't know how to overdub them).

**Comment by ali-ramadhan** [comment]
@glwagner What do you think of renaming `set_ic!`  to `set_initial_conditions!`?

`ic` may be cryptic to some users. You shouldn't have to check the docs to figure out what it does.

**Comment by ali-ramadhan** [comment]
I'll release v0.9.2 once this is merged as a lot of scripts rely on `set_ic!` so would be good to get this in a patch release in case someone is running GPU simulations.

**Comment by glwagner** [comment]
I do not approve of merging this PR. This PR fundamentally changes the way that `set_ic!` (it calculates the `ic` function on the GPU, rather than the CPU), and will fail in many of our use cases.

**Comment by ali-ramadhan** [comment]
Bad practice on my part. Noticed other issues as well. Reverting.

**Pull request merged**
