### PR TITLE
[WIP] Adds a restarter keyword to Model constructor

### PR DESCRIPTION
**Pull request by suyashbire1**
The idea here is to minimize the amount of modifications required to the parent script when model is being restarted from a checkpoint.

Currently, the script might look like this when the model is being run for the first time:
```julia
model = Model(
       architecture = GPU(),
         float_type = Float64,
               grid = RegularCartesianGrid(size=(Nx, Ny, Nz), length=(Lx, Ly, Lz)),
           coriolis = coriolis,
           buoyancy = SeawaterBuoyancy(gravitational_acceleration=g_Europa),
            closure = closure,
boundary_conditions = model_bcs,
            forcing = forcing
)
# model = restore_from_checkpoint(path; kwargs)
```
When restarting from the checkpoint, we'll have to comment the first 9 lines and uncomment the following line. This gets annoying pretty quickly when running a large suite of experiments. So I thought it would be better to integrate the checkpoint specification with model constructor. 

```julia
model = Model(
          restarter = "/path/to/checkpoint/file",
       architecture = GPU(),
         float_type = Float64,
               grid = RegularCartesianGrid(size=(Nx, Ny, Nz), length=(Lx, Ly, Lz)),
           coriolis = coriolis,
           buoyancy = SeawaterBuoyancy(gravitational_acceleration=g_Europa),
            closure = closure,
boundary_conditions = model_bcs,
            forcing = forcing
)
```
Modifications to parent script are minimized if restarting from checkpointer is integrated into model constructor. 

The way I have implemented it currently, if restarter is specified in model constructor all other kwargs to `Model` are ignored. @ali-ramadhan thinks this doesn't cover all possible model specification cases. 

Any thoughts on how to improve this?

### CODE REVIEW

**Comment by glwagner** [comment]
I’m a little hazy on the objective, which makes coming up with design solutions difficult. I think ideal syntax for restarting from a checkpoint would be good topic to discuss in an issue? 

For example, I don’t understand why it’s best to reuse the parent script for restarting. Presumably the ideal syntax for restarting would require just the name of the checkpoint file and a “run”-type command. Of course this can’t be done yet because we don’t have a Simulation type, but it’s be good to design something that will allow such a pattern when we do.

**Comment by suyashbire1** [comment]
Agreed. Let us continue the discussion on #602.

**Comment by glwagner** [comment]
Should we close this PR for the time being?

**Comment by suyashbire1** [comment]
Closing this PR as the new Simulation class and #628 seems to take care of this.

**Pull request closed without merging**
