### PR TITLE
Add default Ω_Earth and R_Earth for FPlane and BetaPlane

### LINKED ISSUE #510: `Ωᵉᵃʳᵗʰ` default for Coriolis constructors?
We also use `gᴱᵃʳᵗʰ` in the buoyancy constructors. It could also make sense to use Earth's rotation rate as a default in the `FPlane` constructor, eg:

```julia
const Ωᴱᵃʳᵗʰ = 7.2921e-5 # https://en.wikipedia.org/wiki/Earth%27s_rotation#Angular_speed
# ...
function FPlane(FT; f=nothing, latitude=nothing, rotation_rate=Ωᴱᵃʳᵗʰ)
# ...
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #510

### CODE REVIEW

**Comment by glwagner** [comment]
How many significant digits would we like to use? The number of digits in each constant is not consistent.

**Comment by ali-ramadhan** [comment]
> How many significant digits would we like to use? The number of digits in each constant is not consistent.

I think we should use as many significant digits as possible up to experimental uncertainty. Why should different constants have the same number of significant digits, especially if they're not always combined?

For `Ω_Earth` we have 7.2921150 ± 0.0000001 × 10^−5 radians per SI second so I updated this PR to use `7.292115e-5`.

For `R_Earth` the _Handbook of Chemistry and Physics_ quotes 6371.0 km for the mean radius of the Earth so I updated the PR to use `6371.0e3`.

**Comment by glwagner** [comment]
I guess that's a fair point. I don't think we use all the significant digits available from experiments for `g_Earth`. Just thought it could be nice to make a decision so we don't end up making arbitrary truncations in cases where constants are known to 42 digits.

Right --- `R_Earth` is a bit ambiguous...

But if the values of such constants are super important to users simulations, its probably best to encourage them to set them explicitly in scripts.

**Comment by ali-ramadhan** [comment]
> Just thought it could be nice to make a decision so we don't end up making arbitrary truncations in cases where constants are known to 42 digits, but we decide not to copy 42 digits into the source code. Kind of happened with the gas constant: https://github.com/climate-machine/CLIMA/pull/496

I think in these cases we should copy over all 42 digits. 

> But if the values of such constants are super important to users simulations, its probably best to encourage them to set them explicitly in scripts.
>
> But, hardly matters at this point since all we do are rectangles...

True.

If it turns out to be a bad idea to assume defaults then we can take them away.

**Pull request merged**
