### PR TITLE
Fixes in docs

### PR DESCRIPTION
**Pull request by navidcy**
I would also suggest to change notation from `v` to `\upsilon` because `v` and `\nu` are very similar.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Woah, first outside contribution, we're becoming a real package! Thanks for fixing the docs url and the LaTeX Stuff. Had no idea `\v{}` gives you bold!

Definitely agree that `v` and `\nu` look similar :( Was thinking of using `\itnu` (or some fancy script `\nu`) instead of `\nu` but haven't tried that yet.

I'm sure it's going to pass but just gonna wait for Travis to complete then merge.

**Comment by navidcy** [comment]
I’d suggest that \nu is kept for viscosity. Change v. 

\v{..} is a macro I just defined. 

Also at some point \mathbf{v} (for velocity vector) became \mathbf{u}. I couldn’t see the reason why so I didn’t interfere. Is there a reason for that?

**Comment by ali-ramadhan** [comment]
Ah yes I see the `\newcommand\v[1]{\boldsymbol{ #1}}` now.

Using `\upsilon` for velocity feels weird to me as it's not used for velocity but I haven't played around with MathJax so not sure what the best variables are. MathJax might not support a lot of extra math fonts anyways. `\nu` looks like a nu so yeah maybe changing v is the way to go?

I don't think there's a reason why `\mathbf{u}` became `\mathbf{v}` besides oversight. I combined the docs from multiple scattered notes and we ended up with slightly inconsistent documentation, so that was my fault. Thanks for pointing this out.

**Comment by navidcy** [comment]
Although is not customary, in reality \upsilon really looks like a calligraphic v. 
If you can’t think of anything else then Give it a go and see how it goes..

**Comment by glwagner** [comment]
I agree that denoting a velocity component with `\nu` is a heinous crime.

**Comment by glwagner** [comment]
I'd prefer the command `\b{}` to bold something.

**Comment by navidcy** [comment]
@glwagner, I don’t think anybody was implying that sort of criminal activity

**Comment by ali-ramadhan** [comment]
Yeah it looked great in LaTeX but I guess MathJax renders variables a little differently.

> Although is not customary, in reality \upsilon really looks like a calligraphic v.
If it makes the documentation more readable, then why not.

**Comment by glwagner** [comment]
We should put a "```math" block at the top of the document to define all the macros and such that we will use later, rather than defining macros in the middle of the document.

It would make it more readable if we have shortcuts like `\bu` for bold velocity and `\bnabla` for bold nabla, etc.

**Comment by navidcy** [comment]
If you hold on merging I change \v{} to \b{} tomorrow. (Late now down under.)

**Comment by ali-ramadhan** [comment]
> We should put a "```math" block at the top of the document to define all the macros and such that we will use later, rather than defining macros in the middle of the document.

That's what I initially did (copied the idea from the FourierFlows.jl docs!) but for some reason it wouldn't work when I compiled the docs on my own computer... I may have been doing it wrong though.

**Comment by glwagner** [comment]
I'd also like `\d` for derivatives rather than `\p` (for partial?), but that is stylistic.

**Comment by ali-ramadhan** [comment]
> I'd also like `\d` for derivatives rather than `\p` (for partial?), but that is stylistic.

Users won't see it so feel free to change to what works best. I usually use `\d` for derivatives and `\p` for partials but here we basically only use partial derivatives.

**Comment by glwagner** [comment]
I also think that we should start to put sentences on different lines. This makes it easier to see changes in the diff. Splitting very long sentences into two lines might be a good idea too.

**Comment by navidcy** [comment]
Indeed, This is indeed a problem with git diff that I found particularly annoying when using github for a manuscript. 

But one should not change his style of writing to accomplish git diff. Git diff is there to serve us not to be served by us.. ha

**Comment by glwagner** [comment]
Which do we want: `\bu` or `\bv` for velocity?

**Comment by ali-ramadhan** [comment]
> I'm working on another commit. What notation do we want @ali-ramadhan: `\bu` or `\bv` for velocity?

Biased answer but I like **v** (`\bv`) for 3D velocity fields and **u** (`\bu`) for 2D velocity fields following [Vallis (2017)](https://www.amazon.com/Atmospheric-Oceanic-Fluid-Dynamics-Fundamentals/dp/110706550X/). Since this is a 3D model my vote is for `\bv`.

**Comment by glwagner** [comment]
The "long line" issue is not just a problem for diff's by the way. I use a text editor (and many others do too) in which navigation is performed by the keyboard. Navigating to the middle of an extremely long line is annoying and time consuming (I could possible build in shortcuts that jump many words at at time for that... but I haven't). Code navigation is more efficient (for me) when the lines are short and I can navigate through the text by jumping lines.

**Comment by glwagner** [comment]
@ali-ramadhan I feel using `\bv` for 3D and `\bu` for 2D may simply be too easy to confuse (our newest contributor Navid was confused!) I think it's more standard is to use a subscript 'h' for horizontal.

**Comment by glwagner** [comment]
It's interesting that Vallis does that. I honestly can't recall any oceanography paper I've ever read using bold 'v' for velocity --- though its not uncommon in engineering or physics.

**Comment by navidcy** [comment]
@glwagner did you tested that commit 4fc55e9 actually works?
As @ali-ramadhan was saying... it doesn't!
(There must be something wrong in the latex code definitions... perhaps a \renewcommand needs to be used.)

also, If I had a vote I'd say \bv for 3D flow and \bv_h for horizontal.

**Comment by ali-ramadhan** [comment]
> @ali-ramadhan I feel using `\bv` for 3D and `\bu` for 2D may simply be too easy to confuse (our newest contributor Navid was confused!) I think it's more standard is to use a subscript 'h' for horizontal.

I wasn't advocating for using both `\bv` and `\bu`, just that we use `\bv` everywhere. The documentation already uses `\bv_h` for horizontal velocity which I agree increases clarity and should be kept.

**Comment by glwagner** [comment]
@navidcy it didn't work --- I'm fixing it.

There's a lot of references to an 'embedded' model. Should we remove these @ali-ramadhan and simply call it a model ? It doesn't seem appropriate for documentation --- the model can be run without embedding it in anything.

**Comment by ali-ramadhan** [comment]
> There's a lot of references to an 'embedded' model. Should we remove these @ali-ramadhan and simply call it a model ? It doesn't seem appropriate for documentation --- the model can be run without embedding it in anything.

Yes, calling it a model and not an embedded model sounds like a good call.

For context, the LaTeX notes I copied from envisioned this model being a super-parameterization or embedded model but this has changed since the notes were typeset.

**Comment by johncmarshall54** [comment]
I also vote for \bv for 3D flow and \bv_h for horizontal. Making it consistent with MITgcm might also be useful if, thinking ahead, we want to wean those fortran users in to Julia.

**Comment by glwagner** [comment]
Okay @johncmarshall54. Changes made.

Unfortunately I implemented that my changes on my own fork, and it seems I can't push to this PR without @navidcy 's permission, I believe... ? (still learning git...)

I suggest we merge this PR, and then I will open another PR for the additional docs changes that I have made. Does that sound good @ali-ramadhan ?

**Comment by ali-ramadhan** [comment]
Sounds good to me!

As @navidcy pointed out, https://github.com/climate-machine/Oceananigans.jl/commit/4fc55e9a6bde7c8547f397cc37b1d1227c1ca3e6 might have broken the docs but sounds like you fixed it on your fork?

**Pull request merged**
