### PR TITLE
Support for horizontal boundary conditions

### PR DESCRIPTION
**Pull request by ali-ramadhan**
With this PR we can now apply boundary conditions on `x` and `y`.

I still need to add tests and benchmark performance (nothing should change).

One discussion point: Should we even add support for `x` boundary conditions seeing as we only support `Periodic` boundary conditions in the `x` direction?

### CODE REVIEW

**Comment by glwagner** [comment]
> One discussion point: Should we even add support for x boundary conditions seeing as we only support Periodic boundary conditions in the x direction?

Probably not, since its best not to have code with no functionality, I think. It's probably actually a good thing that we'd have to reinternalize this functionality in the future (because it means we have to re-review the code) to implement the `x` boundary conditions.

**Comment by johncmarshall54** [comment]
What about a box, though. That would be useful. Gyres etc. John

**Comment by ali-ramadhan** [comment]
> Only comment is that we went with "north, south, east, west" in naming the halo regions functions --- it might make sense to change the name of the `apply_` functions to `apply_y_north_bc` (rather than `apply_y_right_bc` --- etc for all boundaries --- to match this convention.

That makes sense. Should be an easy change.

> Probably not, since its best not to have code with no functionality, I think.

Good point. I'll remove the `x` functions. Less code, less bugs!

> What about a box, though. That would be useful. Gyres etc. John

We'd have to use a 3D discrete cosine transform for the pressure solve. That wouldn't be too hard to implement on the CPU as FFTW can do that out of the box.

But on the GPU, we'd have to code that up ourselves as cuFFT does not do cosine transforms... I was able to implement efficient 1D and 2D cosine transforms on the GPU based on existing literature, but not sure if it's worth implementing a potentially complicated 3D cosine transform unless we need to simulate boxes.

**Comment by glwagner** [comment]
> What about a box, though. That would be useful. Gyres etc. John

To do boxes we need a Poisson solver first (the hard part).

**Comment by glwagner** [comment]
> But on the GPU, we'd have to code that up ourselves as cuFFT does not do cosine transforms... I was able to implement efficient 1D and 2D cosine transforms on the GPU based on existing literature, but not sure if it's worth implementing a potentially complicated 3D cosine transform unless we need to simulate boxes.

We should use the same method on the CPU and GPU that permutes the dimensions of the array. We should not use different solvers on CPU and GPU. Let's not continue this problem as we add more Poisson solvers.

**Comment by ali-ramadhan** [comment]
> We should use the same method on the CPU and GPU that permutes the dimensions of the array. 

The problem is that we can do something more efficient on the CPU with FFTW's cosine transforms (I haven't benchmarked the permutating DCT algorithm on the  CPU, although it's probably safe to assume that FFTW is faster).

We may be able to switch to a a wholly more efficient pressure solver that solves tridiagonal systems in the vertical with PR #306 so then we can get rid of the permutation algorithm for doubly periodic configurations and have fewer Poisson solvers.

**Comment by ali-ramadhan** [comment]
This got a little too messy when I did a `git merge master` as we reversed the k index and added arbitrary tracers since this PR was opened.

I will close this PR and re-implement horizontal boundary conditions in a future PR that will include tests as well.

**Pull request closed without merging**
